# Generated by Django 5.2.5 on 2025-08-23 05:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Professional title or position', max_length=100, verbose_name='title')),
                ('institution', models.CharField(blank=True, help_text='Affiliated institution', max_length=255, verbose_name='institution')),
                ('department', models.CharField(blank=True, help_text='Department or unit', max_length=255, verbose_name='department')),
                ('phone', models.CharField(blank=True, help_text='Contact phone number', max_length=20, verbose_name='phone number')),
                ('orcid_id', models.CharField(blank=True, help_text='ORCID iD (e.g., 0000-0002-1825-0097)', max_length=19, verbose_name='ORCID iD')),
                ('email_confirmed', models.BooleanField(default=False, verbose_name='email confirmed')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='last updated')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'user profile',
                'verbose_name_plural': 'user profiles',
            },
        ),
    ]
